<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompaniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompaniesRepository extends EntityRepository
{
    public function findAllCompanies(): array
    {
        $qb = $this->createQueryBuilder('c');

        $result = $qb->select('c', 'p')
            ->leftJoin('c.positions', 'p')
            ->orderBy('c.name', 'ASC')
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findCompanies($companyId): array
    {
        $qb = $this->createQueryBuilder('c');

        $result = $qb->select('c', 'p')
            ->innerJoin('c.positions', 'p')
            ->where('c.id = :companyId')
            ->setParameters(['companyId' => $companyId])
            ->getQuery()
            ->getResult();

        return $result;
    }
}
