<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompaniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompaniesRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAllPositions()
    {
        $qb = $this->createQueryBuilder('c');

        $result = $qb->select('c', 'p')
            ->leftJoin('c.positions', 'p')
            ->orderBy('c.id', 'ASC')
            ->getQuery()
            ->getResult();

        return $result;
    }
}
