<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PositionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionsRepository extends EntityRepository
{
    public function findPositions($positionId): array
    {
        $qb = $this->createQueryBuilder('p');

        $result = $qb->select('p', 'c')
          ->leftJoin('p.company', 'c')
          ->where('p.id = :positionId')
          ->setParameters(['positionId' => $positionId])
          ->getQuery()
          ->getResult();

        return $result;
    }

    public function findAllPositions(): array
    {
        $qb = $this->createQueryBuilder('p');

        $result = $qb->select('p', 'c')
            ->leftJoin('p.company', 'c')
            ->getQuery()
            ->getResult();

        return $result;
    }
}
