AppBundle\Entity\Positions:
    properties:
        title:
            - NotBlank: ~

        jobDescription:
             - NotBlank: ~

        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true

AppBundle\Entity\Companies:
     properties:
            name:
                - NotBlank: ~
